cubbyhole_user:
    resource: "@CubbyholeUserBundle/Controller/"
    type:     annotation
    prefix:   /

cubbyhole_web_site:
    resource: "@CubbyholeWebSiteBundle/Controller/"
    type:     annotation
    prefix:   /

login: 
    pattern: /login
    default: {_cubbyhole_user: Security/login }
